# Generated by Django 4.0.2 on 2023-04-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerlogin',
            name='pincode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerlogin',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerlogin',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ownerlogin',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ownerlogin',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
