# Generated by Django 4.0.2 on 2023-04-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ownerlogin_pincode_alter_customerlogin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlogin',
            name='fullname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ownerlogin',
            name='fullname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
